export const GET_COMPLAINTS = 'GET_COMPLAINTS';
export const GET_COMPLAINTS_INFO = 'GET_COMPLAINTS_INFO';
export const GET_COMPLAINTS_MESSAGE = 'GET_COMPLAINTS_MESSAGE';
export const GET_COMPLAINTS_ID = 'GET_COMPLAINTS_ID';
