export const GET_NEWS_DATA = 'GET_DATA';
export const GET_NEWS_INFO = 'GET_INFO';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_NEWS_REACTION = 'GET_NEWS_REACTION';
export const SELECTED_FILTER = 'SELECTED_FILTER';
export const SELECTED_FILTER_MONTH = 'SELECTED_FILTER_MONTH';
